[package]
name = "linux_microkit"
edition = '2024'
description = "The seL4 Microkit in a Linux environment"
repository = "https://github.com/mikemospan/linux_microkit"

[dependencies]
libc = "0.2"
roxmltree = "0.20"

[lib]
name = "loader_api"
path = "src/loader.rs"